import{useEffect,useState}from"react";import{ArrowUpRight,Database,FileUp,Loader2,Search,ShieldCheck,Sparkles}from"lucide-react";import Sidebar from"./components/Sidebar";import SourceCard from"./components/SourceCard";import EvidenceGraph from"./components/EvidenceGraph";import{listDocuments,queryRag,uploadDocument,type Document,type QueryResponse}from"./api";
export default function App(){const[page,setPage]=useState("dashboard"),[q,setQ]=useState(""),[res,setRes]=useState<QueryResponse|null>(null),[docs,setDocs]=useState<Document[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sel,setSel]=useState(0);
const refresh=async()=>{try{setDocs(await listDocuments())}catch{}};useEffect(()=>{refresh()},[]);
const run=async()=>{if(!q.trim())return;setBusy(true);setError("");try{setRes(await queryRag(q));setPage("query")}catch(e){setError(e instanceof Error?e.message:"Query failed")}finally{setBusy(false)}};
const upload=async(file:File)=>{setBusy(true);try{await uploadDocument(file);await refresh()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}};
return <div className="shell"><Sidebar active={page} onChange={setPage}/><main><header><div><small>RESEARCH WORKSPACE</small><h1>{page==="dashboard"?"Decision intelligence, grounded in evidence.":page==="query"?"Query Workspace":page==="sources"?"Source Explorer":"Evidence Graph"}</h1></div><span className="pill"><i/> API connected</span></header>{error&&<div className="error">{error}</div>}
{page==="dashboard"&&<section><div className="hero"><div><label>✦ EVIDENCE-FIRST RAG</label><h2>Ask complex questions.<br/><em>See why the answer is true.</em></h2><p>Hybrid retrieval, reranking, evidence mapping and grounded generation in one research workflow.</p><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()} placeholder="Ask about your documents…"/><button onClick={run}>{busy?<Loader2 className="spin" size={17}/>:<ArrowUpRight size={17}/>}</button></div></div><div className="core">TR</div></div><div className="stats"><Stat icon={<Database/>} label="Documents" value={String(docs.length)}/><Stat icon={<FileUp/>} label="Chunks indexed" value={String(docs.reduce((a,d)=>a+d.chunks,0))}/><Stat icon={<ShieldCheck/>} label="Grounding" value="Evidence-first"/><Stat icon={<Sparkles/>} label="Pipeline" value="Online"/></div><div className="panel"><div className="panel-title"><div><small>KNOWLEDGE BASE</small><h3>Indexed documents</h3></div><label className="upload">Upload<input type="file" hidden accept=".pdf,.txt,.md" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div>{docs.length?docs.map(d=><div className="doc" key={d.id}><FileUp size={16}/><div><b>{d.filename}</b><small>{d.chunks} chunks · {(d.size_bytes/1024).toFixed(1)} KB</small></div></div>):<div className="empty">Upload a PDF or text document to begin.</div>}</div></section>}
{page==="query"&&<section><div className="search query-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()} placeholder="Ask a question…"/><button onClick={run}>{busy?<Loader2 className="spin" size={17}/>:"Run query"}</button></div>{res?<div className="query-grid"><div className="panel answer"><div className="answer-head"><div><small>GROUNDED ANSWER</small><h2>{res.answer??"Retrieval complete — add GEMINI_API_KEY for generated answers."}</h2></div><div className="confidence"><small>CONFIDENCE</small><b>{Math.round(res.confidence*100)}%</b></div></div>{res.sub_queries.length>1&&<div className="subs"><small>DECOMPOSED INTO</small>{res.sub_queries.map((x,i)=><span key={i}>{x}</span>)}</div>}<div className="cites"><small>CITATIONS</small>{res.citations.length?res.citations.map((c,i)=><p key={i}><b>[Source {c.source}]</b> {c.claim}</p>):<p>No generated citations. Inspect retrieved evidence on the right.</p>}</div></div><div><small>EVIDENCE</small><h3>{res.sources.length} supporting chunks</h3>{res.sources.map((s,i)=><SourceCard key={s.chunk_id}s={s} i={i} selected={sel===i} onClick={()=>setSel(i)}/>)}</div></div>:<div className="empty big">Ask a question to retrieve and inspect evidence.</div>}</section>}
{page==="sources"&&<section><div className="panel"><div className="panel-title"><div><small>SOURCE EXPLORER</small><h3>Documents</h3></div></div>{docs.map(d=><div className="doc large" key={d.id}><FileUp/><div><b>{d.filename}</b><small>{d.content_type} · {d.chunks} chunks · {d.size_bytes.toLocaleString()} bytes</small></div></div>)}</div></section>}
{page==="graph"&&<section><div className="panel"><div className="panel-title"><div><small>EVIDENCE GRAPH</small><h3>Source relationships</h3></div></div><EvidenceGraph sources={res?.sources??[]}/></div></section>}</main></div>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>}